### ISSUE TITLE
Update content based on feedback

### ISSUE THREAD

**Issue by ifirmawan** [akvo/sahtoso-columbia#4]
## TODO/DONE

- [x] Replace the documentation pdf
- [x] Put Unicef logo . Find an svg if possible . Unicef logo should be easy to find
- [x] Change the tab header to colombia as shown in the gif
- [x] Substitute the words Dashboard and Guideline for their Spanish translations:
    Dashboard = Tablero
    Guideline = Manual de uso
